/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TotaladminresultadoRouteImport } from './routes/totaladminresultado'
import { Route as TotaladminRouteImport } from './routes/totaladmin'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PalpitesRouteImport } from './routes/palpites'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CercamentoRouteImport } from './routes/cercamento'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AcessivelJaRouteImport } from './routes/acessivel-ja'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamTeamNameRouteImport } from './routes/team.$teamName'
import { Route as MatchMatchIdRouteImport } from './routes/match.$matchId'
import { Route as ApiPublicRefreshMatchesRouteImport } from './routes/api/public/refresh-matches'
import { Route as ApiPublicRefreshLiveRouteImport } from './routes/api/public/refresh-live'

const TotaladminresultadoRoute = TotaladminresultadoRouteImport.update({
  id: '/totaladminresultado',
  path: '/totaladminresultado',
  getParentRoute: () => rootRouteImport,
} as any)
const TotaladminRoute = TotaladminRouteImport.update({
  id: '/totaladmin',
  path: '/totaladmin',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PalpitesRoute = PalpitesRouteImport.update({
  id: '/palpites',
  path: '/palpites',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CercamentoRoute = CercamentoRouteImport.update({
  id: '/cercamento',
  path: '/cercamento',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessivelJaRoute = AcessivelJaRouteImport.update({
  id: '/acessivel-ja',
  path: '/acessivel-ja',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamTeamNameRoute = TeamTeamNameRouteImport.update({
  id: '/team/$teamName',
  path: '/team/$teamName',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdRoute = MatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRefreshMatchesRoute = ApiPublicRefreshMatchesRouteImport.update({
  id: '/api/public/refresh-matches',
  path: '/api/public/refresh-matches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRefreshLiveRoute = ApiPublicRefreshLiveRouteImport.update({
  id: '/api/public/refresh-live',
  path: '/api/public/refresh-live',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acessivel-ja': typeof AcessivelJaRoute
  '/auth': typeof AuthRoute
  '/cercamento': typeof CercamentoRoute
  '/dashboard': typeof DashboardRoute
  '/favoritos': typeof FavoritosRoute
  '/history': typeof HistoryRoute
  '/noticias': typeof NoticiasRoute
  '/palpites': typeof PalpitesRoute
  '/privacidade': typeof PrivacidadeRoute
  '/profile': typeof ProfileRoute
  '/termos': typeof TermosRoute
  '/totaladmin': typeof TotaladminRoute
  '/totaladminresultado': typeof TotaladminresultadoRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/team/$teamName': typeof TeamTeamNameRoute
  '/api/public/refresh-live': typeof ApiPublicRefreshLiveRoute
  '/api/public/refresh-matches': typeof ApiPublicRefreshMatchesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acessivel-ja': typeof AcessivelJaRoute
  '/auth': typeof AuthRoute
  '/cercamento': typeof CercamentoRoute
  '/dashboard': typeof DashboardRoute
  '/favoritos': typeof FavoritosRoute
  '/history': typeof HistoryRoute
  '/noticias': typeof NoticiasRoute
  '/palpites': typeof PalpitesRoute
  '/privacidade': typeof PrivacidadeRoute
  '/profile': typeof ProfileRoute
  '/termos': typeof TermosRoute
  '/totaladmin': typeof TotaladminRoute
  '/totaladminresultado': typeof TotaladminresultadoRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/team/$teamName': typeof TeamTeamNameRoute
  '/api/public/refresh-live': typeof ApiPublicRefreshLiveRoute
  '/api/public/refresh-matches': typeof ApiPublicRefreshMatchesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acessivel-ja': typeof AcessivelJaRoute
  '/auth': typeof AuthRoute
  '/cercamento': typeof CercamentoRoute
  '/dashboard': typeof DashboardRoute
  '/favoritos': typeof FavoritosRoute
  '/history': typeof HistoryRoute
  '/noticias': typeof NoticiasRoute
  '/palpites': typeof PalpitesRoute
  '/privacidade': typeof PrivacidadeRoute
  '/profile': typeof ProfileRoute
  '/termos': typeof TermosRoute
  '/totaladmin': typeof TotaladminRoute
  '/totaladminresultado': typeof TotaladminresultadoRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/team/$teamName': typeof TeamTeamNameRoute
  '/api/public/refresh-live': typeof ApiPublicRefreshLiveRoute
  '/api/public/refresh-matches': typeof ApiPublicRefreshMatchesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acessivel-ja'
    | '/auth'
    | '/cercamento'
    | '/dashboard'
    | '/favoritos'
    | '/history'
    | '/noticias'
    | '/palpites'
    | '/privacidade'
    | '/profile'
    | '/termos'
    | '/totaladmin'
    | '/totaladminresultado'
    | '/match/$matchId'
    | '/team/$teamName'
    | '/api/public/refresh-live'
    | '/api/public/refresh-matches'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acessivel-ja'
    | '/auth'
    | '/cercamento'
    | '/dashboard'
    | '/favoritos'
    | '/history'
    | '/noticias'
    | '/palpites'
    | '/privacidade'
    | '/profile'
    | '/termos'
    | '/totaladmin'
    | '/totaladminresultado'
    | '/match/$matchId'
    | '/team/$teamName'
    | '/api/public/refresh-live'
    | '/api/public/refresh-matches'
  id:
    | '__root__'
    | '/'
    | '/acessivel-ja'
    | '/auth'
    | '/cercamento'
    | '/dashboard'
    | '/favoritos'
    | '/history'
    | '/noticias'
    | '/palpites'
    | '/privacidade'
    | '/profile'
    | '/termos'
    | '/totaladmin'
    | '/totaladminresultado'
    | '/match/$matchId'
    | '/team/$teamName'
    | '/api/public/refresh-live'
    | '/api/public/refresh-matches'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcessivelJaRoute: typeof AcessivelJaRoute
  AuthRoute: typeof AuthRoute
  CercamentoRoute: typeof CercamentoRoute
  DashboardRoute: typeof DashboardRoute
  FavoritosRoute: typeof FavoritosRoute
  HistoryRoute: typeof HistoryRoute
  NoticiasRoute: typeof NoticiasRoute
  PalpitesRoute: typeof PalpitesRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ProfileRoute: typeof ProfileRoute
  TermosRoute: typeof TermosRoute
  TotaladminRoute: typeof TotaladminRoute
  TotaladminresultadoRoute: typeof TotaladminresultadoRoute
  MatchMatchIdRoute: typeof MatchMatchIdRoute
  TeamTeamNameRoute: typeof TeamTeamNameRoute
  ApiPublicRefreshLiveRoute: typeof ApiPublicRefreshLiveRoute
  ApiPublicRefreshMatchesRoute: typeof ApiPublicRefreshMatchesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/totaladminresultado': {
      id: '/totaladminresultado'
      path: '/totaladminresultado'
      fullPath: '/totaladminresultado'
      preLoaderRoute: typeof TotaladminresultadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/totaladmin': {
      id: '/totaladmin'
      path: '/totaladmin'
      fullPath: '/totaladmin'
      preLoaderRoute: typeof TotaladminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palpites': {
      id: '/palpites'
      path: '/palpites'
      fullPath: '/palpites'
      preLoaderRoute: typeof PalpitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cercamento': {
      id: '/cercamento'
      path: '/cercamento'
      fullPath: '/cercamento'
      preLoaderRoute: typeof CercamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acessivel-ja': {
      id: '/acessivel-ja'
      path: '/acessivel-ja'
      fullPath: '/acessivel-ja'
      preLoaderRoute: typeof AcessivelJaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamName': {
      id: '/team/$teamName'
      path: '/team/$teamName'
      fullPath: '/team/$teamName'
      preLoaderRoute: typeof TeamTeamNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId': {
      id: '/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof MatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/refresh-matches': {
      id: '/api/public/refresh-matches'
      path: '/api/public/refresh-matches'
      fullPath: '/api/public/refresh-matches'
      preLoaderRoute: typeof ApiPublicRefreshMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/refresh-live': {
      id: '/api/public/refresh-live'
      path: '/api/public/refresh-live'
      fullPath: '/api/public/refresh-live'
      preLoaderRoute: typeof ApiPublicRefreshLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcessivelJaRoute: AcessivelJaRoute,
  AuthRoute: AuthRoute,
  CercamentoRoute: CercamentoRoute,
  DashboardRoute: DashboardRoute,
  FavoritosRoute: FavoritosRoute,
  HistoryRoute: HistoryRoute,
  NoticiasRoute: NoticiasRoute,
  PalpitesRoute: PalpitesRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ProfileRoute: ProfileRoute,
  TermosRoute: TermosRoute,
  TotaladminRoute: TotaladminRoute,
  TotaladminresultadoRoute: TotaladminresultadoRoute,
  MatchMatchIdRoute: MatchMatchIdRoute,
  TeamTeamNameRoute: TeamTeamNameRoute,
  ApiPublicRefreshLiveRoute: ApiPublicRefreshLiveRoute,
  ApiPublicRefreshMatchesRoute: ApiPublicRefreshMatchesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
